---
abstract: 'Catmandu modules for working with Inspire data.'
author:
  - '=over'
build_requires:
  Test::Exception: 0.32
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Inspire
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: 0.8014
  Furl: 0.41
  Moo: 1.004
  XML::LibXML::Simple: 0.93
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-Inspire/issues
  homepage: https://github.com/LibreCat/Catmandu-Inspire
  repository: https://github.com/LibreCat/Catmandu-Inspire.git
version: 0.26
x_contributors:
  - 'Vitali <vitali.peil@uni-bielefeld.de>'
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
